name: Audit and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (fail on ALL vulnerabilities)
        run: npm audit --audit-level=low

      - name: Build project using Vite
        run: npm run build